name: aura_bluetooth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_blue_plus: ^2.0.0
  permission_handler: ^12.0.1
  sensors_plus: ^7.0.0
  flutter_foreground_task: ^9.1.0
  workmanager: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.0.1
  provider: ^6.1.5

  flutter_local_notifications: ^19.4.0
  firebase_auth: ^5.7.0
  firebase_core: ^3.6.0
  # freezed_annotation: ^2.1.0
  # injectable: ^2.0.0
  # activity_recognition_flutter: ^5.0.0 # For user activity
  # light_sensor: ^
  flutter_activity_recognition: ^4.0.0
  # ambient_light: ^0.1.4
  noise_meter: ^5.0.1
  go_router: ^17.0.0
  cloud_firestore: ^5.6.12
  audio_session: ^0.2.2
  just_audio: ^0.10.5
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.5.4
  # freezed: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/